version: "3.8"

services:
  date-server:
    image: date-server:latest
    container_name: date-server
    build:
      context: ./date-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
    depends_on:
      - db